language: python
python:
- 3.5
sudo: required
services:
  - docker
cache:
  directories:
  - eggs
before_install:
- docker-compose -f docker-compose-dev.yml up -d 
install:
- python bootstrap.py
- bin/buildout -N -t 3
- docker ps -a
script: bin/py.test --ldap localhost --ldap-port 10389 --redis localhost --redis-port 6379
after_script:
  - docker-compose stop
  - docker-compose rm -f
