language: python
python:
- 3.5
sudo: required
services:
  - docker
cache:
  directories:
  - eggs
before_install:
- docker-compose -f docker-compose-dev.yml start
install:
- python bootstrap.py
- bin/buildout -N -t 3
script: bin/py.test --ldap $(docker inspect --format '{{ .NetworkSettings.IPAddress }}' ldap) --ldap-port 10389 --redis $(docker inspect --format '{{ .NetworkSettings.IPAddress }}' redis) --redis-port 6379
after_script:
  - docker-compose stop
  - docker-compose rm -f
