language: python
python:
- 3.5
sudo: required
services:
  - docker
cache:
  directories:
  - eggs
before_install:
- docker-compose -f docker-compose-dev.yml start
install:
- python bootstrap.py
- bin/buildout -N -t 3
script: bin/py.test --ldap 127.0.0.1 --ldap-port 10389 --redis 127.0.0.1 --redis-port 6379
after_script:
  - docker-compose stop
  - docker-compose rm -f
