redis:
  image: redis
  ports:
  - "6379:6379"  
ldap:
  image: greggigon/apacheds
  volumes:
  - ./ldap-bootstrap:/bootstrap
  ports:
  - "10389:10389"
  environment:
  - BOOTSTRAP_FILE=/bootstrap/demo.ldif
  restart: always